export const VOTE_PROMPTS = [
  "WHO WOULD SURVIVE THE LONGEST IN JAIL?",
  "WHO IS MOST LIKELY TO START A CULT?",
  "WHO TEXTS THEIR EX?",
  "WHO DIES FIRST IN A HORROR MOVIE?",
  "WHO HAS THE WORST TASTE?",
  "WHO WOULD WIN A BAR FIGHT?",
  "WHO'S HIDING SOMETHING?",
  "WHO GETS THE WORST HANGOVER?",
  "WHO WOULD MARRY FOR MONEY?",
  "WHO IS THE BIGGEST LIAR?",
  "WHO WOULD SURVIVE THE APOCALYPSE?",
  "WHO CAN'T BE TRUSTED WITH A SECRET?",
]

export const LIAR_CLAIMS = [
  "I HAVE A TATTOO I REGRET",
  "I HAVE BEEN ON TV",
  "I CAN LICK MY ELBOW",
  "I HAVE NEVER BROKEN A BONE",
  "I HAVE MET A CELEBRITY",
  "I HAVE FAKED SICK FOR WORK",
  "I HAVE STOLEN SOMETHING",
  "I SPEAK THREE LANGUAGES",
  "I HAVE BEEN IN LOVE THIS YEAR",
  "I HAVE GHOSTED SOMEONE",
  "I CAN DRIVE A MOTORCYCLE",
  "I HAVE CRIED AT A MOVIE THIS MONTH",
]
